#tablero de ajedrez
p1 = ('a2','p','b')
p2 = ('b2','p','b')
p3 = ('c2','p','b')
p4 = ('d2','p','b')
p5 = ('e2','p','b')
p6 = ('f2','p','b')
p7 = ('g2','p','b')
p8 = ('h2','p','b')
t1 = ('a1','t','b')
c1 = ('b1','c','b')
a1 = ('c1','a','b')
reyna = ('d1','reyna','b')
rey = ('e1','rey','b')
a2 = ('f1','a','b')
c2 = ('g1','c','b')
t2 = ('h1','t','b')

np1 = ('a7','p','n')
np2 = ('b7','p','n')
np3 = ('c7','p','n')
np4 = ('d7','p','n')
np5 = ('e7','p','n')
np6 = ('f7','p','n')
np7 = ('g7','p','n')
np8 = ('h7','p','n')
nt1 = ('a8','t','n')
nc1 = ('b8','c','n')
na1 = ('c8','a','n')
nreyna = ('d8','reyna','n')
nrey = ('e8','rey','n')
na2 = ('f8','a','n')
nc2 = ('g8','c','n')
nt2 = ('h8','t','n')

blancas = [p1,p2,p3,p4,p5,p6,p7,p8,t1,c1,a1,t2,c2,reyna,rey]
negras = [np1,np2,np3,np4,np5,np6,np7,np8,nt1,nc1,na1,nt2,nc2,nreyna,nrey]

print(blancas)
print(negras)